// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaP41SR07mdsldyJydTBPrDC3LvtgmTa4',
    appId: '1:764221896013:web:a420dcd8f7b7813f4bb304',
    messagingSenderId: '764221896013',
    projectId: 'join-us-9bf96',
    authDomain: 'join-us-9bf96.firebaseapp.com',
    storageBucket: 'join-us-9bf96.appspot.com',
    measurementId: 'G-366KBJNKJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIe_MAimlA5hRP60-0B9TpJwteaz6JCuo',
    appId: '1:764221896013:android:8afe6a7fc01233614bb304',
    messagingSenderId: '764221896013',
    projectId: 'join-us-9bf96',
    storageBucket: 'join-us-9bf96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDst6WXQI6krpz7wUOLKcxn-mCAyCXEVn8',
    appId: '1:764221896013:ios:7cec0bcdc23bd2894bb304',
    messagingSenderId: '764221896013',
    projectId: 'join-us-9bf96',
    storageBucket: 'join-us-9bf96.appspot.com',
    iosBundleId: 'com.example.joinUs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDst6WXQI6krpz7wUOLKcxn-mCAyCXEVn8',
    appId: '1:764221896013:ios:7cec0bcdc23bd2894bb304',
    messagingSenderId: '764221896013',
    projectId: 'join-us-9bf96',
    storageBucket: 'join-us-9bf96.appspot.com',
    iosBundleId: 'com.example.joinUs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaP41SR07mdsldyJydTBPrDC3LvtgmTa4',
    appId: '1:764221896013:web:4e3397a175c019de4bb304',
    messagingSenderId: '764221896013',
    projectId: 'join-us-9bf96',
    authDomain: 'join-us-9bf96.firebaseapp.com',
    storageBucket: 'join-us-9bf96.appspot.com',
    measurementId: 'G-4F3M94ZE9P',
  );

}